name: epsilon-reverse-proxy

services:
  rp:
    container_name: epsilon-rp
    build:
      dockerfile: Dockerfile-external
    networks:
      - epsilon-network
  rp-internal:
    container_name: epsilon-rp-internal
    build:
      dockerfile: Dockerfile-internal
    networks:
      - epsilon-network

networks:
  epsilon-network:
    external: true